### Simple MLP Regression

The y variable is a vector

In [8]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# load data
import pandas as pd
df = pd.read_csv("all-county-data-no-tmpprecip.csv")

# dealing with nas
df['VACO2'].isna().sum()

# replace with median (not sure which method to choose)
VACO2_median = df['VACO2'].median()
df['VACO2'].fillna(VACO2_median, inplace=True)

# min-max predictors
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

cols_select = ['Income', 'DSCI', 'VACO2'] 
scaler = MinMaxScaler()
#scaler = StandardScaler()

scaled_cols = scaler.fit_transform(df[cols_select])
scaled_df = pd.DataFrame(scaled_cols, columns=cols_select)

cols_add = ['County','Year','Agriculture', 'Aquaculture','Barren','Developed', 'Forest','Grassland','Open_Water','Shrubland','Wetlands']
scaled_df[cols_add] = df[cols_add]

# replacing County with numeric value
scaled_df['County'].replace(['Accomack', 'Fauquier', 'Greensville', 'Hanover', 'Rockingham', 'Wise'],
                        [1,2,3,4,5,6], inplace=True)

# one-hot code year
onehot = pd.get_dummies(scaled_df['Year'])
df_scaled = pd.concat([scaled_df, onehot], axis=1)

# drop the original year column
df_scaled.drop('Year', axis=1, inplace=True)

# scaled data
df_scaled.T

0             1             2             3     \
Income           0.090254      0.084485      0.088903      0.108869   
DSCI             0.595959      0.091255      0.090562      0.164876   
VACO2            1.000000      0.422880      0.740739      0.242746   
County       51067.000000  51067.000000  51067.000000  51067.000000   
Agriculture      0.120512      0.103555      0.087572      0.088977   
Aquaculture      0.000000      0.000000      0.000000      0.000000   
Barren           0.000806      0.001854      0.001828      0.002897   
Developed        0.042941      0.042546      0.040608      0.042279   
Forest           0.663460      0.662633      0.660032      0.672473   
Grassland        0.145732      0.161879      0.181759      0.166330   
Open_Water       0.026327      0.027040      0.027313      0.026095   
Shrubland        0.000216      0.000486      0.000887      0.000917   
Wetlands         0.000005      0.000007      0.000000      0.000031   
2008             1.000000      0.000000      0.000000      0.000000   
2009             0.000000      1.000000      0.000000      0.000000   
2010             0.000000      0.000000      1.000000      0.000000   
2011             0.000000      0.000000      0.000000      1.000000   
2012             0.000000      0.000000      0.000000      0.000000   
2013             0.000000      0.000000      0.000000      0.000000   
2014             0.000000      0.000000      0.000000      0.000000   
2015             0.000000      0.000000      0.000000      0.000000   
2016             0.000000      0.000000      0.000000      0.000000   
2017             0.000000      0.000000      0.000000      0.000000   
2018             0.000000      0.000000      0.000000      0.000000   
2019             0.000000      0.000000      0.000000      0.000000   
2020             0.000000      0.000000      0.000000      0.000000   
2021             0.000000      0.000000      0.000000      0.000000   
2022             0.000000      0.000000      0.000000      0.000000   

                     4             5             6             7     \
Income           0.122916      0.122004      0.137874      0.156553   
DSCI             0.203418      0.052459      0.073621      0.143967   
VACO2            0.032386      0.415422      0.504482      0.513963   
County       51067.000000  51067.000000  51067.000000  51067.000000   
Agriculture      0.086611      0.082118      0.083991      0.137212   
Aquaculture      0.000000      0.000000      0.000000      0.000000   
Barren           0.003506      0.001318      0.001346      0.005751   
Developed        0.042493      0.042105      0.046297      0.045958   
Forest           0.673071      0.667200      0.653685      0.679065   
Grassland        0.166485      0.180652      0.184273      0.099269   
Open_Water       0.026633      0.026327      0.027358      0.027184   
Shrubland        0.001170      0.000279      0.002978      0.005530   
Wetlands         0.000031      0.000002      0.000073      0.000031   
2008             0.000000      0.000000      0.000000      0.000000   
2009             0.000000      0.000000      0.000000      0.000000   
2010             0.000000      0.000000      0.000000      0.000000   
2011             0.000000      0.000000      0.000000      0.000000   
2012             1.000000      0.000000      0.000000      0.000000   
2013             0.000000      1.000000      0.000000      0.000000   
2014             0.000000      0.000000      1.000000      0.000000   
2015             0.000000      0.000000      0.000000      1.000000   
2016             0.000000      0.000000      0.000000      0.000000   
2017             0.000000      0.000000      0.000000      0.000000   
2018             0.000000      0.000000      0.000000      0.000000   
2019             0.000000      0.000000      0.000000      0.000000   
2020             0.000000      0.000000      0.000000      0.000000   
2021             0.000000      0.000000     

In [36]:
df_scaled.isna().sum()

Income         450
DSCI             0
VACO2            0
County           0
Agriculture     45
Aquaculture     45
Barren          45
Developed       45
Forest          45
Grassland       45
Open_Water      45
Shrubland       45
Wetlands        45
2008             0
2009             0
2010             0
2011             0
2012             0
2013             0
2014             0
2015             0
2016             0
2017             0
2018             0
2019             0
2020             0
2021             0
2022             0
dtype: int64

In [35]:
# split into X and y dataframes

y_vars = ['Agriculture', 'Aquaculture','Barren','Developed', 'Forest','Grassland','Open_Water','Shrubland','Wetlands']
x_vars = df_scaled.columns[~df_scaled.columns.isin(y_vars)]

y = df_scaled[y_vars]
X = df_scaled[x_vars]

X["Income"].isna().sum() # 450
# X["VACO2"].isna().sum() # 0
# X["DSCI"].isna().sum() # 0

#temp = X[X["Income"].isna()]# 450
#temp
y.isna().sum()

Agriculture    45
Aquaculture    45
Barren         45
Developed      45
Forest         45
Grassland      45
Open_Water     45
Shrubland      45
Wetlands       45
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
# leave out some counties- take 80pct of counties for train and rest for test?

# Try again without hard coding the numbers - take an 80% fraction or so
# did not shuffle so that the years would stay in order... but not sure that worked...
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, shuffle=False, random_state=42)

# NEXT TIME SPLIT BY COUNTIES/FIPS CODES
# make list of training and eval fips code


# save input parameters to np.array
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# (interpolation function (BEFORE SCALING)) ?? Not sure anymore what inperpolating meanss
# imputing - handling missing data 

## How to deal with the years when one hot encoded like this?

print(X_train)
print('----')
print(y_train)

[[0.09025402 0.59595897 1.         ... 0.         0.         0.        ]
 [0.08448514 0.09125466 0.42288031 ... 0.         0.         0.        ]
 [0.08890295 0.0905619  0.74073902 ... 0.         0.         0.        ]
 ...
 [       nan 0.01221767 0.01182606 ... 1.         0.         0.        ]
 [       nan 0.15775909 0.         ... 0.         1.         0.        ]
 [       nan 0.06864567 0.44645648 ... 0.         0.         1.        ]]
----
[[1.20511508e-01 0.00000000e+00 8.06190134e-04 ... 2.63274060e-02
  2.15830430e-04 5.37134553e-06]
 [1.03555147e-01 0.00000000e+00 1.85409082e-03 ... 2.70403300e-02
  4.85862619e-04 7.32456209e-06]
 [8.75724643e-02 0.00000000e+00 1.82772239e-03 ... 2.73132920e-02
  8.87248621e-04 0.00000000e+00]
 ...
 [1.87277541e-01 0.00000000e+00 6.59639548e-04 ... 2.07958145e-02
  1.14095051e-02 2.39910000e-04]
 [1.58816936e-01 0.00000000e+00 3.67296100e-04 ... 2.09132888e-02
  1.02856461e-02 1.67609905e-04]
 [1.54770472e-01 0.00000000e+00 4.77067552e-04 ... 

#### Fit the Model

In [13]:
# Fit the simple model
# HAVE CELL TO DEFINE HYPERPARAMETERS
# try setting and adding activation function (logistic / softmax / tanh)
# try to make it sum to number
# floor values (np.clip())

regr = MLPRegressor(hidden_layer_sizes=(100,),
                    random_state=1, 
                    activation='logistic',
                    learning_rate_init=0.01, 
                    learning_rate='adaptive',
                    max_iter=500000).fit(X_train, y_train)

ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

#### Make Predictions

In [79]:
# Make predictions for test data

regr.predict(X_test[:1])

array([[ 0.16352232,  0.01110836, -0.00264411,  0.07434502,  0.65651641,
         0.16768583, -0.00207587,  0.01401712, -0.05169422]])

In [80]:
y_test[:1]

array([[2.42847564e-01, 0.00000000e+00, 8.81364203e-04, 7.14916137e-02,
        5.92571897e-01, 8.84974808e-02, 2.88111531e-03, 6.65219150e-04,
        1.63746252e-04]])

In [81]:
# Make this all a function for each row!! This makes is like softmax
floored = np.clip(regr.predict(X_test[:1]), 0,1)
sums = np.sum(floored)
floored/sums

array([[0.15040753, 0.01021745, 0.        , 0.06838241, 0.60386258,
        0.15423711, 0.        , 0.01289292, 0.        ]])

In [82]:
# compute mse instead of r^2 (Actual-predicted etc.)

In [83]:
# could compare mse and r^2 for each column to see what land use it's best at predicting

#### Calc R-squared

In [84]:
# Calculate R-squared

regr.score(X_test, y_test)

-386687.77663841913

In [85]:
regr.predict(X_train[:1])

array([[ 0.26599741,  0.02257287, -0.00319977,  0.08792585,  0.30953277,
         0.06292007,  0.01499567,  0.02365697,  0.34047509]])

In [86]:
regr.score(X_train, y_train)

-4906.541127867366

In [9]:
# 